### ISSUE TITLE
프로젝트 초기 세팅 & 환경 구축

### ISSUE THREAD

**Issue by Wo-ogie** [Zelusik/server-scraping#1]
## 🔥 Issue
프로젝트 초기 세팅 & 환경 구축

## ✅ TODO
- [x] Pull request template 추가
- [x] Logging 환경 구축
- [x] Swagger 설정
- [x] Error handling 환경 구축
- [x] logback 설정

**Comment by Wo-ogie** [comment]
API request/response에 대한 logger를 filter로 등록하지 않아 해당 log가 찍히지 않고 있다.
이에 issue를 reopen하여 api request/response에 대한 정상적으로 로그를 남기고자 한다.

**Comment by Wo-ogie** [comment]
로그 출력 형식 설정 및 로그 파일을 남기기 위해 logback 설정을 하고자 한다.
해당 사항을 todo로 추가한다.
